# Pacotes necessários ----
library(tidyverse)
library(lubridate)
library(visdat)
library(ggridges)
library(plotly)
library(skimr)
library(gridExtra)
library(ggstatsplot)
library(PRROC)
library(h2o)